#!/bin/bash
set -euo pipefail

PERSISTENT_HOME="/data/home/openclaw"
ZSHRC_PATH="${PERSISTENT_HOME}/.zshrc"
ZSHRC_BASE_PATH="${PERSISTENT_HOME}/.zshrc.base"

mkdir -p /data
mkdir -p /data/home
mkdir -p /data/pkg/npm-global/lib
mkdir -p /data/pkg/npm-global/bin
mkdir -p /data/pkg/npm-cache
mkdir -p /data/pkg/pnpm
mkdir -p /data/pkg/pnpm-store
mkdir -p /data/pkg/python-user
mkdir -p /data/pkg/pip-cache
mkdir -p "${PERSISTENT_HOME}/.config"
mkdir -p "${PERSISTENT_HOME}/.cache"
mkdir -p "${PERSISTENT_HOME}/.local/share"
mkdir -p "${PERSISTENT_HOME}/.local/state"

chown -R openclaw:openclaw /data
chmod 700 /data

if [ ! -f "${PERSISTENT_HOME}/.bootstrap-complete" ]; then
  cp -a /home/openclaw/. "${PERSISTENT_HOME}/" 2>/dev/null || true
  touch "${PERSISTENT_HOME}/.bootstrap-complete"
fi

# Always regenerate .zshrc.base so updates in new images take effect immediately
printf '%s\n' '# AUTO-GENERATED by entrypoint.sh — do not edit this file directly' > "${ZSHRC_BASE_PATH}"
printf '%s\n' '# Edit ~/.zshrc for your own customizations' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' '' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' '# --- persistent package paths ---' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export PATH="/data/pkg/npm-global/bin:/data/pkg/pnpm:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export SHELL="/bin/zsh"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export ZDOTDIR="${HOME}"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export XDG_CONFIG_HOME="${HOME}/.config"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export XDG_CACHE_HOME="${HOME}/.cache"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export XDG_DATA_HOME="${HOME}/.local/share"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export XDG_STATE_HOME="${HOME}/.local/state"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export NPM_CONFIG_PREFIX="/data/pkg/npm-global"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export NPM_CONFIG_CACHE="/data/pkg/npm-cache"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export NPM_CONFIG_USERCONFIG="${HOME}/.npmrc"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export PNPM_HOME="/data/pkg/pnpm"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export PNPM_STORE_DIR="/data/pkg/pnpm-store"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export PYTHONUSERBASE="/data/pkg/python-user"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export PIP_CACHE_DIR="/data/pkg/pip-cache"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export HOMEBREW_CACHE="${HOME}/.cache/Homebrew"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' '' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' '# --- oh-my-zsh ---' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'export ZSH="/opt/oh-my-zsh"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'ZSH_THEME="robbyrussell"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'plugins=(git z sudo colored-man-pages command-not-found)' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' '[ -f "$ZSH/oh-my-zsh.sh" ] && source "$ZSH/oh-my-zsh.sh"' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' '' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' '# --- completions (after compinit) ---' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' 'if ! (( $+functions[compdef] )); then autoload -Uz compinit && compinit; fi' >> "${ZSHRC_BASE_PATH}"
printf '%s\n' '[ -f "/data/.openclaw/completions/openclaw.zsh" ] && source "/data/.openclaw/completions/openclaw.zsh"' >> "${ZSHRC_BASE_PATH}"

# Create .zshrc only on first boot; afterwards users can freely customize it
if [ ! -f "${ZSHRC_PATH}" ]; then
  printf '%s\n' '# Source the managed base config (env, oh-my-zsh, completions)' > "${ZSHRC_PATH}"
  printf '%s\n' '[ -f "${HOME}/.zshrc.base" ] && source "${HOME}/.zshrc.base"' >> "${ZSHRC_PATH}"
  printf '%s\n' '' >> "${ZSHRC_PATH}"
  printf '%s\n' '# --- your customizations below this line ---' >> "${ZSHRC_PATH}"
fi

chown -R openclaw:openclaw "${PERSISTENT_HOME}"

rm -rf /home/openclaw
ln -sfn "${PERSISTENT_HOME}" /home/openclaw

if [ ! -d /data/.linuxbrew ]; then
  cp -a /home/linuxbrew/.linuxbrew /data/.linuxbrew
fi

rm -rf /home/linuxbrew/.linuxbrew
ln -sfn /data/.linuxbrew /home/linuxbrew/.linuxbrew

export HOME=/home/openclaw
export SHELL=/bin/zsh
export ZDOTDIR=/home/openclaw
export XDG_CONFIG_HOME=/home/openclaw/.config
export XDG_CACHE_HOME=/home/openclaw/.cache
export XDG_DATA_HOME=/home/openclaw/.local/share
export XDG_STATE_HOME=/home/openclaw/.local/state
export NPM_CONFIG_PREFIX=/data/pkg/npm-global
export NPM_CONFIG_CACHE=/data/pkg/npm-cache
export NPM_CONFIG_USERCONFIG=/home/openclaw/.npmrc
export PNPM_HOME=/data/pkg/pnpm
export PNPM_STORE_DIR=/data/pkg/pnpm-store
export PYTHONUSERBASE=/data/pkg/python-user
export PIP_CACHE_DIR=/data/pkg/pip-cache
export HOMEBREW_CACHE=/home/openclaw/.cache/Homebrew
export PATH="/data/pkg/npm-global/bin:/data/pkg/pnpm:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:${PATH}"

exec gosu openclaw node src/server.js
